### ISSUE TITLE
Could not find or load main class org.apache.flink.yarn.entrypoint.YarnJobClusterEntrypoint

### ISSUE THREAD

**Issue by fanxl12** [todd5167/flink-spark-submiter#13]
Idea本地运行提交到yarn上面之后，提示Error: Could not find or load main class org.apache.flink.yarn.entrypoint.YarnJobClusterEntrypoint错误，放在服务器上运行是正常的

**Comment by noneDirection** [comment]
我也遇到了 但是yarn的环境变量设置了 还是不行 怎么解决

**Comment by todd5167** [comment]
> 

本地是windows系统吧

**Comment by fanxl12** [comment]
@todd5167 是的

**Comment by todd5167** [comment]
> @todd5167 是的

 window 系统提交不上去，mac和 linux系统都可以的。

**Comment by todd5167** [comment]
> > @todd5167 是的
> 
> window 系统提交不上去，mac和 linux系统都可以的。

@fanxl12 @noneDirection
