### ISSUE TITLE
Can UDF be supported

### ISSUE THREAD

**Issue by lingya** [todd5167/flink-spark-submiter#3]
Can UDF  be supported？

**Comment by todd5167** [comment]
@lingya Can support, I will write a demo to add to the examples。

**Comment by todd5167** [comment]
@lingya  UDF和你本身的Flink任务有关，这个项目负责提交构建后的jobgraph

**Comment by lingya** [comment]
> @lingya  UDF和你本身的Flink任务有关，这个项目负责提交构建后的jobgraph

好的
